In [1]:
from astropy import units as u
from astropy import constants as const
import numpy as np

Here are the cyclotron harmonics and orders from Parsons et al. 2021 for SDSS J2229+1853.

In [2]:
n2_wave=6400 *u.angstrom
n3_wave=4250*u.angstrom
n4_wave=3200*u.angstrom

In [3]:
n2_wave=5987. *u.angstrom
n3_wave=4250*u.angstrom
n4_wave=3200*u.angstrom

In [4]:
def wave_to_freq(wave):
    return (const.c/wave).to(u.Hz)

In [5]:
def freq_to_wave(freq):
    return (const.c/freq).to(u.angstrom)

In [6]:
def get_waves(b_field):
    fun_freq=((const.e.to(u.C)*b_field.to(u.MG))/(2*np.pi*const.m_e)).to(u.Hz)
    freqs=fun_freq*(np.array([1,2,3,4]))
    waves=freq_to_wave(freqs)
    return waves

In [7]:
def get_B_field(freq):
    print('freq',freq)
    return (2 * np.pi * const.m_e * freq/ (const.e).to(u.C)).to(u.MG)

In [8]:
get_B_field(44555.3*u.Hz)


freq 44555.3 Hz


<Quantity 1.59168763e-08 MG>

In [9]:
b_fields=np.array([1.0,5.0,10.0,15.0,20.0,50.0,100.0,150.0])*u.MG
for b_field in b_fields:
    waves=get_waves(b_field)
    print('B=',b_field,'cyclotron wavelengths:',waves.to(u.micron))
    print(wave_to_freq(waves).to(u.Hz))
    
waves=get_waves(1000.*u.T)
print(wave_to_freq(waves).to(u.Hz))

B= 1.0 MG cyclotron wavelengths: [107.09746056  53.54873028  35.69915352  26.77436514] micron
[2.79924899e+12 5.59849797e+12 8.39774696e+12 1.11969959e+13] Hz
B= 5.0 MG cyclotron wavelengths: [21.41949211 10.70974606  7.1398307   5.35487303] micron
[1.39962449e+13 2.79924899e+13 4.19887348e+13 5.59849797e+13] Hz
B= 10.0 MG cyclotron wavelengths: [10.70974606  5.35487303  3.56991535  2.67743651] micron
[2.79924899e+13 5.59849797e+13 8.39774696e+13 1.11969959e+14] Hz
B= 15.0 MG cyclotron wavelengths: [7.1398307  3.56991535 2.37994357 1.78495768] micron
[4.19887348e+13 8.39774696e+13 1.25966204e+14 1.67954939e+14] Hz
B= 20.0 MG cyclotron wavelengths: [5.35487303 2.67743651 1.78495768 1.33871826] micron
[5.59849797e+13 1.11969959e+14 1.67954939e+14 2.23939919e+14] Hz
B= 50.0 MG cyclotron wavelengths: [2.14194921 1.07097461 0.71398307 0.5354873 ] micron
[1.39962449e+14 2.79924899e+14 4.19887348e+14 5.59849797e+14] Hz
B= 100.0 MG cyclotron wavelengths: [1.07097461 0.5354873  0.35699154 0.267

In [10]:
def get_harmonics(wave,guessed_n):
    test_list=[1,2,3,4]
    test_list.remove(guessed_n)
    freq=wave_to_freq(wave)
    other_freqs=np.array(test_list)/float(guessed_n)*freq
    #print(test_list,"other_freqs",other_freqs)
    if guessed_n == 1:
        fundamental_freq=freq
    else:
        fundamental_freq=other_freqs[np.where(np.array(test_list)==1)]
    mag_field=get_B_field(fundamental_freq)
    print('B field:',mag_field,mag_field.to(u.T))
    other_waves=freq_to_wave(other_freqs)
    print(test_list,"other_waves",other_waves)
    return

In [11]:
j1113_peak=3900 * u.angstrom

In [12]:
for guessed_n in [1,2,3,4]:
    print('\n\n----')
    print('guessed_n',guessed_n)
    get_harmonics(j1113_peak, guessed_n)
    print('\n\n----')



----
guessed_n 1
freq 768698610256410.1 Hz
B field: 274.60887322358894 MG 27460.887322358896 T
[2, 3, 4] other_waves [1950. 1300.  975.] Angstrom


----


----
guessed_n 2
freq [3.84349305e+14] Hz
B field: [137.30443661] MG [13730.44366118] T
[1, 3, 4] other_waves [7800. 2600. 1950.] Angstrom


----


----
guessed_n 3
freq [2.5623287e+14] Hz
B field: [91.53629107] MG [9153.62910745] T
[1, 2, 4] other_waves [11700.  5850.  2925.] Angstrom


----


----
guessed_n 4
freq [1.92174653e+14] Hz
B field: [68.65221831] MG [6865.22183059] T
[1, 2, 3] other_waves [15600.  7800.  5200.] Angstrom


----


In [13]:
for guessed_n in [1,2,3,4]:
    print('\n\n----')
    print('guessed_n',guessed_n)
    get_harmonics(n2_wave,guessed_n)
    print('\n\n----')



----
guessed_n 1
freq 500739031234341.0 Hz
B field: 178.88334818306282 MG 17888.33481830628 T
[2, 3, 4] other_waves [2993.5        1995.66666667 1496.75      ] Angstrom


----


----
guessed_n 2
freq [2.50369516e+14] Hz
B field: [89.44167409] MG [8944.16740915] T
[1, 3, 4] other_waves [11974.          3991.33333333  2993.5       ] Angstrom


----


----
guessed_n 3
freq [1.6691301e+14] Hz
B field: [59.62778273] MG [5962.77827277] T
[1, 2, 4] other_waves [17961.    8980.5   4490.25] Angstrom


----


----
guessed_n 4
freq [1.25184758e+14] Hz
B field: [44.72083705] MG [4472.08370458] T
[1, 2, 3] other_waves [23948.         11974.          7982.66666667] Angstrom


----


In [14]:
for guessed_n in [1,2,3,4]:
    print('\n\n----')
    print('guessed_n',guessed_n)
    get_harmonics(n3_wave,guessed_n)
    print('\n\n----')



----
guessed_n 1
freq 705394018823529.4 Hz
B field: 251.9940248404699 MG 25199.40248404699 T
[2, 3, 4] other_waves [2125.         1416.66666667 1062.5       ] Angstrom


----


----
guessed_n 2
freq [3.52697009e+14] Hz
B field: [125.99701242] MG [12599.70124202] T
[1, 3, 4] other_waves [8500.         2833.33333333 2125.        ] Angstrom


----


----
guessed_n 3
freq [2.3513134e+14] Hz
B field: [83.99800828] MG [8399.80082802] T
[1, 2, 4] other_waves [12750.   6375.   3187.5] Angstrom


----


----
guessed_n 4
freq [1.76348505e+14] Hz
B field: [62.99850621] MG [6299.85062101] T
[1, 2, 3] other_waves [17000.          8500.          5666.66666667] Angstrom


----


In [15]:
test_list=[1,2,3,4]
test_list.remove(2)

In [16]:
print(test_list)

[1, 3, 4]


In [17]:
for guessed_n in [1,2,3,4]:
    print('\n\n----')
    print('guessed_n',guessed_n)
    get_harmonics(j1113_peak, guessed_n)
    print('\n\n----')



----
guessed_n 1
freq 768698610256410.1 Hz
B field: 274.60887322358894 MG 27460.887322358896 T
[2, 3, 4] other_waves [1950. 1300.  975.] Angstrom


----


----
guessed_n 2
freq [3.84349305e+14] Hz
B field: [137.30443661] MG [13730.44366118] T
[1, 3, 4] other_waves [7800. 2600. 1950.] Angstrom


----


----
guessed_n 3
freq [2.5623287e+14] Hz
B field: [91.53629107] MG [9153.62910745] T
[1, 2, 4] other_waves [11700.  5850.  2925.] Angstrom


----


----
guessed_n 4
freq [1.92174653e+14] Hz
B field: [68.65221831] MG [6865.22183059] T
[1, 2, 3] other_waves [15600.  7800.  5200.] Angstrom


----


In [18]:
for guessed_n in [1,2,3,4]:
    print('\n----')
    print('guessed_n',guessed_n)
    get_harmonics(j1113_peak-100*u.angstrom, guessed_n)
    print('----')


----
guessed_n 1
freq 788927521052631.5 Hz
B field: 281.83542251894664 MG 28183.542251894665 T
[2, 3, 4] other_waves [1900.         1266.66666667  950.        ] Angstrom
----

----
guessed_n 2
freq [3.94463761e+14] Hz
B field: [140.91771126] MG [14091.77112595] T
[1, 3, 4] other_waves [7600.         2533.33333333 1900.        ] Angstrom
----

----
guessed_n 3
freq [2.6297584e+14] Hz
B field: [93.94514084] MG [9394.51408396] T
[1, 2, 4] other_waves [11400.  5700.  2850.] Angstrom
----

----
guessed_n 4
freq [1.9723188e+14] Hz
B field: [70.45885563] MG [7045.88556297] T
[1, 2, 3] other_waves [15200.          7600.          5066.66666667] Angstrom
----


In [19]:
for guessed_n in [1,2,3,4]:
    print('\n----')
    print('guessed_n',guessed_n)
    get_harmonics(j1113_peak-200*u.angstrom, guessed_n)
    print('----')


----
guessed_n 1
freq 810249886486486.4 Hz
B field: 289.4525961005398 MG 28945.259610053978 T
[2, 3, 4] other_waves [1850.         1233.33333333  925.        ] Angstrom
----

----
guessed_n 2
freq [4.05124943e+14] Hz
B field: [144.72629805] MG [14472.62980503] T
[1, 3, 4] other_waves [7400.         2466.66666667 1850.        ] Angstrom
----

----
guessed_n 3
freq [2.70083295e+14] Hz
B field: [96.4841987] MG [9648.41987002] T
[1, 2, 4] other_waves [11100.  5550.  2775.] Angstrom
----

----
guessed_n 4
freq [2.02562472e+14] Hz
B field: [72.36314903] MG [7236.31490251] T
[1, 2, 3] other_waves [14800.          7400.          4933.33333333] Angstrom
----


From page 686 of B.O.B., cyclotron frequency is given by:

$$ \nu_c = \frac{e B}{2 \pi m_e} $$

So solving that back for the magnetic field, we get

$$ B = \frac{2 \pi m_e \nu_c}{e} $$

In [20]:
bfield=get_B_field(2.8e13 * u.Hz)

freq 28000000000000.0 Hz


In [21]:
print(bfield.to(u.T))

1000.268290805899 T


In [22]:
4488-4639

-151

In [23]:
for guessed_n in range(1,10):
    new_list=[1,2,3,4,5,6,7,8,9]
    print('\n----')
    print('guessed_n',guessed_n)
    get_harmonics(j1113_peak-100*u.angstrom, guessed_n,test_list=new_list)
    print('----')


----
guessed_n 1


TypeError: get_harmonics() got an unexpected keyword argument 'test_list'

In [ ]:
range(1,10)

In [ ]:
for thing in range(1,10):
    print(thing)

In [ ]:
(5000*u.T).to(u.MG)