In [1]:
from astropy import units as u
from astropy import constants as const
import numpy as np

Here are the cyclotron harmonics and orders from Parsons et al. 2021 for SDSS J2229+1853.

In [2]:
n2_wave=6400 *u.angstrom
n3_wave=4250*u.angstrom
n4_wave=3200*u.angstrom

In [3]:
def wave_to_freq(wave):
    return (const.c/wave).to(u.Hz)

In [4]:
def freq_to_wave(freq):
    return (const.c/freq).to(u.angstrom)

In [5]:
def get_waves(b_field):
    fun_freq=((const.e.to(u.C)*b_field.to(u.MG))/(2*np.pi*const.m_e)).to(u.Hz)
    freqs=fun_freq*(np.array([1,2,3,4]))
    waves=freq_to_wave(freqs)
    return waves

In [6]:
def get_B_field(freq):
    print('freq',freq)
    return (2 * np.pi * const.m_e * freq/ (const.e).to(u.C)).to(u.MG)

In [7]:
get_B_field(44555.3*u.Hz)


freq 44555.3 Hz


<Quantity 1.59168763e-08 MG>

In [18]:
b_fields=np.array([1.0,5.0,10.0,15.0,20.0,50.0,100.0,150.0])*u.MG
for b_field in b_fields:
    waves=get_waves(b_field)
    print('B=',b_field,'cyclotron wavelengths:',waves.to(u.micron))
    print(wave_to_freq(waves).to(u.Hz))
    
waves=get_waves(1000.*u.T)
print(wave_to_freq(waves).to(u.Hz))

B= 1.0 MG cyclotron wavelengths: [107.09746056  53.54873028  35.69915352  26.77436514] micron
[2.79924899e+12 5.59849797e+12 8.39774696e+12 1.11969959e+13] Hz
B= 5.0 MG cyclotron wavelengths: [21.41949211 10.70974606  7.1398307   5.35487303] micron
[1.39962449e+13 2.79924899e+13 4.19887348e+13 5.59849797e+13] Hz
B= 10.0 MG cyclotron wavelengths: [10.70974606  5.35487303  3.56991535  2.67743651] micron
[2.79924899e+13 5.59849797e+13 8.39774696e+13 1.11969959e+14] Hz
B= 15.0 MG cyclotron wavelengths: [7.1398307  3.56991535 2.37994357 1.78495768] micron
[4.19887348e+13 8.39774696e+13 1.25966204e+14 1.67954939e+14] Hz
B= 20.0 MG cyclotron wavelengths: [5.35487303 2.67743651 1.78495768 1.33871826] micron
[5.59849797e+13 1.11969959e+14 1.67954939e+14 2.23939919e+14] Hz
B= 50.0 MG cyclotron wavelengths: [2.14194921 1.07097461 0.71398307 0.5354873 ] micron
[1.39962449e+14 2.79924899e+14 4.19887348e+14 5.59849797e+14] Hz
B= 100.0 MG cyclotron wavelengths: [1.07097461 0.5354873  0.35699154 0.267

In [9]:
def get_harmonics(wave,guessed_n,test_list=[1,2,3,4]):
    test_list.remove(guessed_n)
    freq=wave_to_freq(wave)
    other_freqs=np.array(test_list)/float(guessed_n)*freq
    #print(test_list,"other_freqs",other_freqs)
    if guessed_n == 1:
        fundamental_freq=freq
    else:
        fundamental_freq=other_freqs[np.where(np.array(test_list)==1)]
    mag_field=get_B_field(fundamental_freq)
    print('B field:',mag_field,mag_field.to(u.T))
    other_waves=freq_to_wave(other_freqs)
    print(test_list,"other_waves",other_waves)
    return

In [10]:
j1113_peak=3900 * u.angstrom

In [11]:
for guessed_n in [1,2,3,4]:
    print('\n\n----')
    print('guessed_n',guessed_n)
    get_harmonics(j1113_peak, guessed_n)
    print('\n\n----')



----
guessed_n 1
freq 768698610256410.1 Hz
B field: 274.60887322358894 MG 27460.887322358896 T
[2, 3, 4] other_waves [1950. 1300.  975.] Angstrom


----


----
guessed_n 2
freq [] Hz
B field: [] MG [] T
[3, 4] other_waves [2600. 1950.] Angstrom


----


----
guessed_n 3
freq [] Hz
B field: [] MG [] T
[4] other_waves [2925.] Angstrom


----


----
guessed_n 4
freq [] Hz
B field: [] MG [] T
[] other_waves [] Angstrom


----


In [12]:
for guessed_n in [1,2,3,4]:
    print('\n\n----')
    print('guessed_n',guessed_n)
    get_harmonics(n2_wave,guessed_n)
    print('\n\n----')



----
guessed_n 1


ValueError: list.remove(x): x not in list

In [ ]:
for guessed_n in [1,2,3,4]:
    print('\n\n----')
    print('guessed_n',guessed_n)
    get_harmonics(n3_wave,guessed_n)
    print('\n\n----')

In [ ]:
test_list=[1,2,3,4]
test_list.remove(2)

In [ ]:
print(test_list)

In [ ]:
for guessed_n in [1,2,3,4]:
    print('\n\n----')
    print('guessed_n',guessed_n)
    get_harmonics(j1113_peak, guessed_n)
    print('\n\n----')

In [ ]:
for guessed_n in [1,2,3,4]:
    print('\n----')
    print('guessed_n',guessed_n)
    get_harmonics(j1113_peak-100*u.angstrom, guessed_n)
    print('----')

In [ ]:
for guessed_n in [1,2,3,4]:
    print('\n----')
    print('guessed_n',guessed_n)
    get_harmonics(j1113_peak-200*u.angstrom, guessed_n)
    print('----')

From page 686 of B.O.B., cyclotron frequency is given by:

$$ \nu_c = \frac{e B}{2 \pi m_e} $$

So solving that back for the magnetic field, we get

$$ B = \frac{2 \pi m_e \nu_c}{e} $$

In [ ]:
bfield=get_B_field(2.8e13 * u.Hz)

In [ ]:
print(bfield.to(u.T))

In [ ]:
4488-4639

In [ ]:
for guessed_n in range(1,10):
    new_list=[1,2,3,4,5,6,7,8,9]
    print('\n----')
    print('guessed_n',guessed_n)
    get_harmonics(j1113_peak-100*u.angstrom, guessed_n,test_list=new_list)
    print('----')

In [ ]:
range(1,10)

In [ ]:
for thing in range(1,10):
    print(thing)

In [ ]:
(5000*u.T).to(u.MG)